# Profile section
profile:
  first_name: David Pedroza Segoviano
  last_name: Bubu
  picture: https://avatars.githubusercontent.com/u/50858626?v=4   # GitHub Picture
  # picture: static/img/rodo_2021.png  # Local picture
  contact:
    address_one: Leon, Guanajuato
    address_two:
    phone: 
  email: david.pedroza.segoviano@gmail.com
  description: |
    I am a quick learner Physics undergraduate student with
    background in mathematics, programming and data
    analysis. I have knowledge of algorithms for complex
    problems, optimization and time complexity calculus. I
    know how to be persistent and work under pressure. Besides
    that, I find teamwork and helping others as one of my major skills.


# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - python
  - html5
  - css3-alt
  - js-square
  - markdown
  - git-alt
  - github
  - google-drive
  - slack
  - trello
  - windows
extra_skills:
  - Physics - EM, Classical Mechanics, Quantum Physcis, etc.
  - Mathematics - Linear Algebra, Differential Equations, Complex Variable, etc.
  - Data Analysis with Python
  - Web Development
  - Machine Learning and Deep Learning
  - Flask, Django, NumPy, Matplotlib, TensorFlow, Pandas, etc.


# Social section
social:
  github: https://github.com/BubuDavid/
  facebook: https://www.facebook.com/DavidWeroBubu/
  linkedin: https://www.linkedin.com/in/davidpedrozasegoviano/
  youtube: https://www.youtube.com/channel/UCaQLn15OcwwGr_skoUEmB_Q


# Certifications and awards section
awards:
  - '3rd. Place in Lince-Hack 2019, Celaya Institute of Technology, 2019'
  - '2nd. National Place - World Educational Robot Contest Mexico, 2016'
  - 'Gold medal - Estatal Olympiad in Informatics, Investigation Math Center (CIMAT), 2016'
  - '1st. Place - Fedemáticas, Leon Guanajuato Federation of Particular Schools, 2017'
  - '3rd. Place - Hack-león Seguridad Total, Leon General Directorate of innovation, 2019'
  - '1st. Place - Scholar Physicist Olympiad, La Salle University, 2017'
  - '1st. Place - Scholar Math Olympiad, La Salle University, 2017'
  - 'Best Video - World Educational Robot Contest, Video Category, 2016'
  - 'Bronze Medal - Estatal Olympiad in Informatics, 2015'

# Projects section
projects:
  item1:
    title: flask-resume-template
    subtitle: A resume template built with Flask - fork from Rodolfo Ferro
    description: An easy-to-configure simple resume template built with Flask and Bootstrap.
    github: https://github.com/BubuDavid/flask-resume-template
    img: flask-resume-template.png
    tags: [Flask, Python, Bootstrap]
  item2:
    title: Scientific and Technology presential talks and workshops
    subtitle: Talks to kids and high school people (Cecyt 17, Salle, etc...).
    description: Talks with the purpose of encourage young people to pursuit a scientific or technological career. 
    link: https://www.facebook.com/golf.fisica/photos/a.117680670079960/125956765919017
    github:
    img: talks1.jpg
    tags: [Flask, Python, Bootstrap]
  item3:
    title: Sharedu
    subtitle: WebPage to share education
    description: Webpage for sharing challenges, contests, courses and hackathons, for all young people that wants to build knowledge.
    link: 
    github: 
    img: 
    tags: [Django, Python, Webpage, HTML, JS, CSS]
  item4:
    title: Future Lab YouTube Channel
    subtitle: Courses, Workshops and Speaks to learn!
    description: As a member of Future Lab I disseminate science, make technology speaks and elaborate courses completely free in our youtube channel 
    link: https://www.youtube.com/c/FutureLabmx/videos
    github:
    img: fl_channel.png
    tags: [Python, Videos, Youtube, technology, puppies]
  item5:
    title: YouTube Channel
    subtitle: Technologic and Scientific Channel
    description: A work in progress youtube channel for tech lovers, science curious and geeks.
    link: https://www.youtube.com/channel/UCaQLn15OcwwGr_skoUEmB_Q
    github:
    img: youtube_channel.png
    tags: [YouTube, Videos, Python, Physics]
  item6:
    title: Web Page with Iris flower classification
    subtitle: A decision tree built inside a web page
    description: With help of Rodolfo Ferro and Zaid de Anda we made a functional web page with BULMA CSS framework and a decision tree built in python to classify iris flowers by sepal and petal length
    link: https://flask-challenge.glitch.me/
    github: https://github.com/BubuDavid/Flask_Challenge
    img: iris.png
    tags: [Python, Machine Learning, Web Platform, Flask, Decision tree, BULMA]
  item7:
    title: Analyzing tweets with python
    subtitle: Playing with the Twitter API and preprocessing more than 100 tweets.
    description: Our main objective is to provide a model capable of recognizing trends in young people, this will help us create events related to these trends so that more people are interested.
    link:
    github: https://github.com/BubuDavid/Analyzing-Tweets-with-Python
    img: twitter.png
    tags: [Python, NLP, Keras, Twitter]


# Community section:
community:
  item0:
    institution: Future Lab
    program: Coordinator
    description: "I am a coordinator at Future Lab, a community full of students, tech lovers, passionate developers and science enthusiasts that work together with great fellowship. We have 4 main objectives:
    1. Develop social, academic and personal projects with technology.
    2. Disseminate science and technic knowledge, with courses, workshops and speaks, accessible for everyone!
    3. Help other communities and projects with common goals.
    4. Participate and help others to participate in hackathons or different kind of contests or challenges."
    from: April 2018
    to: Present
    link: https://futurelab.mx
  item3:
    institution: Organized Group of Physics Undergrads (GOLF)
    program: Community member
    description: Community Member of GOLF (its acronym in Spanish), organized group full of passionate students of Guanajuato University, aiming for the expansion of scientific knowledge mainly physics, and strive for creation of student environment that is inclusive, welcoming, and healthy among our university campus and also inside of the community GOLF itself.
    from: October 2020
    to: Present
    link: https://www.facebook.com/golf.fisica
  item4:
    institution: Leon Youth Scientific Society (SJC)
    program: Community member
    description: Community of dissemination of science and creator of many workshop to wake scientific curiousing in young people. "In today's youth is the science of the future"
    from: August 2018
    to: December 2019
    link: https://scj.org.mx/


# Talks and workshops section
workshops:
  item0:
    event: PROTON-VIVE MEXICO,
    workshop: International certification.
    material:
    link: http://www.protoncertification.org/
  item1:
    event: Santander
    workshop: 'Introducción a las habildades digitales'
    material:
    link: http://santander.skills.anuies.mx/
  item2:
    event: Clubes de Ciencia México 2019.
    workshop: Workshop – Revealing the Hidden Hyperspectrum with Artificial Neurons, July 2019.
    material: https://rodolfoferro.xyz/hyperspectrum/
    link:
  item3:
    event: LAB León Web Dev Crash Course 2019.
    workshop: Crash Course – Introduction to Web Development with Python and Flask, August 2019, I was helping as an intern.
    material: https://github.com/RodolfoFerro/Flask101
    link: https://flask101.glitch.me
  item4:
    event: How to make your first web page for a hackathon.
    workshop: Workshop – Webpage Delepment, August 2019.
    material: 
    link:
  item5:
    event: Lab León 
    workshop: Workshop - Taller prototipo para la apertura y uso de datos abiretos, June 2019
    material: 
    link: https://drive.google.com/file/d/1IR0NGFYts6i0eCFKRVEfRcpChndB_-ho/view?usp=sharing
  item6:
    event: Taller de Ciencia para Jóvenes.
    workshop: Participation in the workshop, July 2019.
    material: https://drive.google.com/file/d/19poUjHOm93Cj-2nG0SZq8QpWkPs6FLOb/view?usp=sharing
    link:


# Education section
education:
  item1:
    institution: University of Guanajuato / DCI
    program: Bachelor of Science in Physics
    description: Major in Physics with Data Science and Machine Learning as terminal area.
    from: August 2018
    to: Present
  item2:
    institution: De la Salle Bajio Campus Americas
    program: High School
    description: Graduated from mathematical physics area.
    from: August 2015
    to: July 2018
